### ISSUE TITLE
Package issues

### ISSUE THREAD

**Issue by ddnexus** [Relik77/bitwise-operation#1]
Nice little package. Just a few distribution glitches.

- The types declaration is not found when you import it in a ts file. The `files` declaration of `package.json` includes only `index.js`.

- E.g. if you manually add the `index.ts` of the root repo in the package (optionally renaming it as `index.d.ts`), it does find the declarations in `./lib`

- Despite the form `Bitwise(...)` is indicated in all the examples in the Readme, it does not work without the `new`.

Thanks

**Comment by Relik77** [comment]
Thanks for the comment,

I hadn't updated this package in a while, thought it wasn't really used (sad)

I'm going to get back to it and update the documentation too (during the JS to TS update, there were some side effects)

**Comment by Relik77** [comment]
A new version is available.
It fixes the types declaration problem.

The notation without the keyword ```new``` cannot be carried in Typescript, a new static method has been created:
```ts
Bitwise.chain(value)
```
This is to make ```new Bitwise(value).themethod(...)``` more readable by writing instead: ```Bitwise.chain(value).themethod(...)```
(Because if it's more readable, we save time to understand and we limit bugs)

Eg.
```ts
new Bitwise(this.rights)
  .and(rights)
  .equals(rights);

// same as :
Bitwise.chain(this.rights)
       .and(rights)
       .equals(rights);
```

**Comment by ddnexus** [comment]
Great solution! Thank you!
